### ISSUE TITLE
started with password pre-set will encounter an error `tornado.httpclient.HTTPClientError: HTTP 403: Forbidden`

### ISSUE THREAD

**Issue by HongW2019** [jupyter-server/jupyter_server#1008]
## Description

When I install jupyter_server above 1.16.0,  running `jupyter lab stop` to shut down server started with password pre-set will encounter an error `tornado.httpclient.HTTPClientError: HTTP 403: Forbidden`

```
# jupyter lab stop
Shutting down server on 8888...
Traceback (most recent call last):
  File "/root/miniconda2/envs/master/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/extension/application.py", line 594, in launch_instance
    serverapp.start()
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 2814, in start
    self.start_app()
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 2710, in start_app
    super().start()
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_core/application.py", line 258, in start
    self.subapp.start()
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 608, in start
    self._shutdown_or_exit(port, server)
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 583, in _shutdown_or_exit
    if not self.shutdown_server(server):
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 579, in shutdown_server
    return shutdown_server(server, log=self.log)
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 516, in shutdown_server
    raise ex
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 512, in shutdown_server
    headers={"Authorization": "token " + server_info["token"]},
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/jupyter_server/utils.py", line 352, in fetch
    response = HTTPClient(AsyncHTTPClient).fetch(request)
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/tornado/httpclient.py", line 135, in fetch
    functools.partial(self._async_client.fetch, request, **kwargs)
  File "/root/miniconda2/envs/master/lib/python3.7/site-packages/tornado/ioloop.py", line 529, in run_sync
    return future_cell[0].result()
tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
```
Same to [#4386](https://github.com/jupyter/notebook/issues/4386)

## Reproduce

```
pip install jupyter_server==1.19.1 jupyterlab
jupyter lab password 
nohup jupyter lab --no-browser  > /tmp/jupyterlab.log 2>&1 &
jupyter lab stop
```

## Expected behavior

`jupyter lab stop` can shut down server with password pre-set scenario.

## Context

- Operating System and version:
- Browser and version:
- Jupyter Server version: above 1.16.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by maawoo** [comment]
I'm running into the same issue. Are there any alternative ways to stop Jupyter Server instances that are running in the background?

**Comment by allstrive** [comment]
I could not reproduce the problem
Env : Python 3.8 
OS : Debian GNU/Linux 11 (bullseye)
@HongW2019 / @maawoo  are you still experiencing this problem
