### ISSUE TITLE
In OpenWRT python 3.9 version, webbrowser module is not existing

### ISSUE THREAD

**Issue by gbrault** [jupyter-server/jupyter_server#1094]
## Description

Launching jupyter lab in OpenWRT results in: ModuleNotFoundError: No module named 'webbrowser'

## Reproduce

Install jupyter lab in an appropriate OpenWRT machine.
OpenWRT python don't have the webbrowser module installed in python package

## Expected behavior

As a web browser is not needed for a server, importing webserver should be optional ( --no-browser option)?

## Context

File "/home/pyuser/.local/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 28, in <module>
    import webbrowser

```
(venv) pyuser@GL-MT2500:~$ jupyter lab --ip 0.0.0.0
Traceback (most recent call last):
  File "/home/pyuser/.local/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/home/pyuser/.local/lib/python3.9/site-packages/jupyterlab/labapp.py", line 13, in <module>
    from jupyter_server.serverapp import flags
  File "/home/pyuser/.local/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 28, in <module>
    import webbrowser
ModuleNotFoundError: No module named 'webbrowser'
(venv) pyuser@GL-MT2500:~$ jupyter lab
Traceback (most recent call last):
  File "/home/pyuser/.local/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/home/pyuser/.local/lib/python3.9/site-packages/jupyterlab/labapp.py", line 13, in <module>
    from jupyter_server.serverapp import flags
  File "/home/pyuser/.local/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 28, in <module>
    import webbrowser
ModuleNotFoundError: No module named 'webbrowser'
```

<details><summary>Components version</summary>
<pre>
IPython          : 8.6.0
jupyter_core     : 5.0.0
jupyter_server   : 1.23.3
jupyterlab       : 3.5.0
nbformat         : 5.7.0
notebook         : 6.5.2
traitlets        : 5.5.0
</pre>
</details>

**Comment by blink1073** [comment]
Hi @gbrault, there is a `--no-browser` argument that you can pass to `jupyter lab`, `jupyter notebook`, or `jupyter_server`.

**Comment by gbrault** [comment]
@blink1073 agreed but dispite this switch,Jupiter server triés to import webbrowser module which is not part of thé python package in openwrt release

**Comment by blink1073** [comment]
Ah, I see what you mean.  We can defer the import.  Would you like to submit a PR?

**Comment by gbrault** [comment]
@blink1073 I am not really hacking this code: just using it, if needed I can do so, but if you can handle it would be easier for me! Please, let me know.
