### ISSUE TITLE
2.0.1: documentation uses `pkg_resources`

### ISSUE THREAD

**Issue by kloczek** [jupyter-server/jupyter_server#1125]
Despite move to `hatchling` as pep517 backend looks like documentation still needs `pkg_resources` whicj is part of the `setuptools`.
```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v5.3.0
Initializing GitHub plugin

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/openapi/__init__.py", line 12, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 462, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.openapi (exception: No module named 'pkg_resources')

Extension error:
Could not import extension sphinxcontrib.openapi (exception: No module named 'pkg_resources')
```
As `pkg_resources` already is marked as deprecated it would be good to switch to `importlib-metadata` module.

**Comment by kloczek** [comment]
Actually looks like pkg_resources is used to find`jupyter-server` version which is in 
```console
[tkloczko@pers-jacek jupyter_server-2.0.1]$ grep -r ^__version__
jupyter_server/_version.py:__version__ = "2.0.1"
```
so instead process module metadata version can be taken straght from module.

**Comment by kloczek** [comment]
Wrong .. `pkg_resources` is used in `sphinxcontrib-openapi` (sorry I'm tired a bit) however looks like doc/ssources/conf.py could be diplifird by drop use `importlib.metadata` and ead version straght from module variable.
