### ISSUE TITLE
Interesting test fail on 2.3.0 in `test_connection`

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-server/jupyter_server#1215]
## Description

On [conda-forge](https://github.com/conda-forge/jupyter_server-feedstock/pull/122),  `test_connection[jp_server_config0]` is throwing the following interesting [traceback](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=658893&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d):

<details><pre>
2023-02-15T15:10:48.3635381Z HTTPServerRequest(protocol='http', host='localhost:45797', method='GET', uri='/a%40b/api/kernels/22e4b383-512f-4a67-b1de-6c0d3e1a3e89/channels', version='HTTP/1.1', remote_ip='127.0.0.1')
2023-02-15T15:10:48.3636173Z Traceback (most recent call last):
2023-02-15T15:10:48.3636750Z   File "$PREFIX/lib/python3.11/site-packages/tornado/web.py", line 1713, in _execute
2023-02-15T15:10:48.3637187Z     result = await result
2023-02-15T15:10:48.3637576Z              ^^^^^^^^^^^^
2023-02-15T15:10:48.3638156Z   File "$PREFIX/lib/python3.11/site-packages/jupyter_server/services/kernels/websocket.py", line 67, in get
2023-02-15T15:10:48.3638656Z     await super().get(kernel_id=kernel_id)
2023-02-15T15:10:48.3639241Z   File "$PREFIX/lib/python3.11/site-packages/tornado/websocket.py", line 277, in get
2023-02-15T15:10:48.3639715Z     await self.ws_connection.accept_connection(self)
2023-02-15T15:10:48.3640483Z   File "$PREFIX/lib/python3.11/site-packages/tornado/websocket.py", line 867, in accept_connection
2023-02-15T15:10:48.3641008Z     await self._accept_connection(handler)
2023-02-15T15:10:48.3641648Z   File "$PREFIX/lib/python3.11/site-packages/tornado/websocket.py", line 950, in _accept_connection
2023-02-15T15:10:48.3642285Z     await self._receive_frame_loop()
2023-02-15T15:10:48.3642857Z   File "$PREFIX/lib/python3.11/site-packages/tornado/websocket.py", line 1106, in _receive_frame_loop
2023-02-15T15:10:48.3643871Z     await self._receive_frame()
2023-02-15T15:10:48.3644680Z   File "$PREFIX/lib/python3.11/site-packages/tornado/websocket.py", line 1195, in _receive_frame
2023-02-15T15:10:48.3645235Z     handled_future = self._handle_message(opcode, data)
2023-02-15T15:10:48.3645677Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-15T15:10:48.3646212Z   File "$PREFIX/lib/python3.11/site-packages/tornado/websocket.py", line 1234, in _handle_message
2023-02-15T15:10:48.3646731Z     self.close(self.close_code)
2023-02-15T15:10:48.3647256Z   File "$PREFIX/lib/python3.11/site-packages/tornado/websocket.py", line 1263, in close
2023-02-15T15:10:48.3647770Z     self._write_frame(True, 0x8, close_data)
2023-02-15T15:10:48.3648401Z   File "$PREFIX/lib/python3.11/site-packages/tornado/websocket.py", line 1061, in _write_frame
2023-02-15T15:10:48.3648984Z     return self.stream.write(frame)
2023-02-15T15:10:48.3649376Z            ^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-15T15:10:48.3649868Z   File "$PREFIX/lib/python3.11/site-packages/tornado/iostream.py", line 540, in write
2023-02-15T15:10:48.3650496Z     self._write_buffer.append(data)
2023-02-15T15:10:48.3651029Z   File "$PREFIX/lib/python3.11/site-packages/tornado/iostream.py", line 157, in append
2023-02-15T15:10:48.3651522Z     b += data  # type: ignore
2023-02-15T15:10:48.3651883Z     ^^^^^^^^^
2023-02-15T15:10:48.3652324Z BufferError: Existing exports of data: object cannot be re-sized
</pre></details>

Going to re-kick, and will probably add to test skips if it is persistent, but this seemed like it could be a Bad Thing.

## Reproduce

Building on conda-forge, with tests and coverage.

## Expected behavior

Presumably pass?

## Context

- Operating System and version: linux (fedora-based), cpython 3.10
- Browser and version: n/a
- Jupyter Server version: 2.3.0

**Comment by bollwyvl** [comment]
Maybe related:
- https://github.com/tornadoweb/tornado/issues/2271
- https://github.com/python/cpython/issues/85269

**Comment by bollwyvl** [comment]
I didn't see it again on a rebuild, or on the subsequent deployment. Nothing to see here (until next time)
