### ISSUE TITLE
Issues trying to calculate schema file location for new event schema

### ISSUE THREAD

**Issue by lresende** [jupyter-server/jupyter_server#1238]
Trying to work on some new events on Jupyter Server around gateway client and found an issue calculating schema location.
We use the following code to calculate the schema location:
```
rel_schema_path = schema_id.lstrip(JUPYTER_SERVER_EVENTS_URI) + ".yaml"
```
and the issue is that lstrip aggressively tries to replace multiple combinations of characters.
in this case, 
```
JUPYTER_SERVER_EVENTS_URI = 'https://events.jupyter.org/jupyter_server'
```
The schema id was
```
https://events.jupyter.org/jupyter_server/gateway/gatewayclient
```
And the issue was that lstrip (see https://docs.python.org/3/library/stdtypes.html#str.lstrip)  removed the **'/g'** as one substring from the  JUPYTER_SERVER_EVENTS_URI being asked to be lstriped which causes the exception below.

```
/Users/lresende/.conda/envs/jupyter-server/bin/python /Users/lresende/.conda/envs/jupyter-server/bin/jupyter-server 
Traceback (most recent call last):
  File "/Users/lresende/.conda/envs/jupyter-server/bin/jupyter-server", line 8, in <module>
    sys.exit(main())
  File "/Users/lresende/.conda/envs/jupyter-server/lib/python3.8/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/Users/lresende/.conda/envs/jupyter-server/lib/python3.8/site-packages/traitlets/config/application.py", line 1042, in launch_instance
    app.initialize(argv)
  File "/Users/lresende/.conda/envs/jupyter-server/lib/python3.8/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/Users/lresende/dev/aiml-jupyter/aiml-jupyter-server/jupyter_server/serverapp.py", line 2526, in initialize
    self.init_event_logger()
  File "/Users/lresende/dev/aiml-jupyter/aiml-jupyter-server/jupyter_server/serverapp.py", line 1971, in init_event_logger
    self.event_logger.register_event_schema(schema_path)
  File "/Users/lresende/.conda/envs/jupyter-server/lib/python3.8/site-packages/jupyter_events/logger.py", line 140, in register_event_schema
    event_schema = self.schemas.register(schema)
  File "/Users/lresende/.conda/envs/jupyter-server/lib/python3.8/site-packages/jupyter_events/schema_registry.py", line 46, in register
    schema = EventSchema(schema)
  File "/Users/lresende/.conda/envs/jupyter-server/lib/python3.8/site-packages/jupyter_events/schema.py", line 70, in __init__
    _schema = self._load_schema(schema)
  File "/Users/lresende/.conda/envs/jupyter-server/lib/python3.8/site-packages/jupyter_events/schema.py", line 121, in _load_schema
    raise EventSchemaFileAbsent(msg)
jupyter_events.schema.EventSchemaFileAbsent: Schema file not present at path "/Users/lresende/dev/jupyter/jupyter-server/jupyter_server/event_schemas/ateway/gatewayclient.yaml".

Process finished with exit code 1
```

PR coming soon

**Comment by Zsailer** [comment]
Good catch, and thank you for the fix!
