### ISSUE TITLE
'NoneType' object has no attribute 'kernel_ws_protocol'

### ISSUE THREAD

**Issue by Carreau** [jupyter-server/jupyter_server#1265]
## Description

```
<tornado internals>
jupyter_server/jupyter_server/services/kernels/websocket.py", line 87, in select_subprotocol
        preferred_protocol = self.connection.kernel_ws_protocol
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'kernel_ws_protocol'
```

## Reproduce

I have a custom kernel (https://github.com/carreau/inplace_restarter), and trying to use it sometime logs this error in the terminal.

It looks like `self.connection` is None, 

It itself is set from 

```
    @property
    def kernel_websocket_connection_class(self):
        """The kernel websocket connection class."""
        return self.settings.get("kernel_websocket_connection_class")

```

Which I guess returns None ? 

## Expected behavior

Handle it being None, or raise a better/earlier error message

**Comment by romangershgorin** [comment]
@Carreau did you manage to debug this issue, why this error happens? I am experiencing the same error and failed so far to understand why connection is None.

**Comment by Carreau** [comment]
No I was not able to find the time to debug/fix.

**Comment by zhijunyuu** [comment]
Hi,

just want to know is there any solution for this? I am already stuck with this for 5 days.
I have conda R and python environments, it worked pretty fine with jupyterlab until last Friday. 
I tried re-install my conda environments, jupyterlab worked perfect fine with python environment, this error occurs whenever I connect a R environment to it. 

Here are some examples of the error I met:
`[W 2024-02-07 21:13:27.579 ServerApp] Timeout waiting for kernel_info reply from 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[I 2024-02-07 21:13:27.585 ServerApp] Connecting to kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83.
[W 2024-02-07 21:13:37.662 ServerApp] Nudge: attempt 10 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[I 2024-02-07 21:13:39.411 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2024-02-07 21:13:39.412 ServerApp] kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83 restarted
[E 2024-02-07 21:13:39.413 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x7f6752186a60>> failed
    Traceback (most recent call last):
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_server/services/kernels/connection/channels.py", line 785, in on_kernel_restarted
        self._send_status_message("restarting")
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_server/services/kernels/connection/channels.py", line 780, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/tornado/websocket.py", line 331, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-02-07 21:13:39.416 ServerApp] kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83 restarted
[E 2024-02-07 21:13:39.416 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x7f67517cd940>> failed
    Traceback (most recent call last):
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_server/services/kernels/connection/channels.py", line 785, in on_kernel_restarted
        self._send_status_message("restarting")
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_server/services/kernels/connection/channels.py", line 780, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/tornado/websocket.py", line 331, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-02-07 21:13:39.417 ServerApp] kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83 restarted
[E 2024-02-07 21:13:39.417 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x7f67517cd9d0>> failed
    Traceback (most recent call last):
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_server/services/kernels/connection/channels.py", line 785, in on_kernel_restarted
        self._send_status_message("restarting")
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_server/services/kernels/connection/channels.py", line 780, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/tornado/websocket.py", line 331, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-02-07 21:13:39.417 ServerApp] kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83 restarted
[E 2024-02-07 21:13:39.417 ServerApp] KernelRestarter: restart callback <bound method ZMQChannelsWebsocketConnection.on_kernel_restarted of <jupyter_server.services.kernels.connection.channels.ZMQChannelsWebsocketConnection object at 0x7f67517f54c0>> failed
    Traceback (most recent call last):
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_client/restarter.py", line 105, in _fire_callbacks
        callback()
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_server/services/kernels/connection/channels.py", line 785, in on_kernel_restarted
        self._send_status_message("restarting")
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/jupyter_server/services/kernels/connection/channels.py", line 780, in _send_status_message
        self.write_message(json.dumps(msg, default=json_default))
      File "zyu/miniconda3/envs/python3.9/lib/python3.9/site-packages/tornado/websocket.py", line 331, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[W 2024-02-07 21:13:39.417 ServerApp] kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83 restarted
[W 2024-02-07 21:13:39.487 ServerApp] Replacing stale connection: 8944e649-06ff-45ff-98ae-ab3f9fa20a83:45434165-abea-41dc-9dec-c0a025dedbf5
[W 2024-02-07 21:13:42.675 ServerApp] Nudge: attempt 20 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[W 2024-02-07 21:13:47.690 ServerApp] Nudge: attempt 30 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[W 2024-02-07 21:13:52.707 ServerApp] Nudge: attempt 40 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[W 2024-02-07 21:13:57.722 ServerApp] Nudge: attempt 50 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[W 2024-02-07 21:14:02.739 ServerApp] Nudge: attempt 60 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[W 2024-02-07 21:14:07.755 ServerApp] Nudge: attempt 70 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[W 2024-02-07 21:14:12.769 ServerApp] Nudge: attempt 80 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83
[W 2024-02-07 21:14:17.784 ServerApp] Nudge: attempt 90 on kernel 8944e649-06ff-45ff-98ae-ab3f9fa20a83`

**Comment by minrk** [comment]
`self.connection` will be None if the connection has been closed. It should be handled as an early close and likely just `return` in this method.
