### ISSUE TITLE
NoOpCheckpoints

### ISSUE THREAD

**Issue by miraculixx** [jupyter-server/jupyter_server#1348]
## Description

Implementing a `NoOpCheckpoints` checkpoints class for a custom ContentsManager results in a `Unhandled error` being raised when opening a notebook in Jupyter Lab.

## Reproduce

1. Create a new ContentsManager class (e.g. subclass FileContentsManager) 
2. Create the `NoOpCheckpoints` as shown in the [documentation](https://jupyter-server.readthedocs.io/en/latest/developers/contents.html#no-op-example)
3. Set the `checkpoints_class = NoOpCheckpoints` trait
4. Run Jupyter lab and try creating a new notebook
5. This will result in error shown above in the severs' log, and a modal dialog presented to the user

![image](https://github.com/jupyter-server/jupyter_server/assets/859611/c427f6b6-0e95-46e0-ac33-25a801d5331c)

## Expected behavior

This used to work 

## Context

This should work, or the documentation should be changed.

- Operating System and version: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
- Python 3.10.12, 
- Browser and version: Google Chrome Version 118.0.5993.88 (Official Build) (64-bit)
- Jupyter Server version:jupyter_server==2.9.0

<details><summary>Troubleshoot Output</summary>
<pre>
$ pip freeze | grep -i jup
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter-telemetry==0.1.0
jupyter_client==8.4.0
jupyter_core==5.4.0
jupyter_server==2.9.0
jupyter_server_terminals==0.4.4
jupyterhub==4.0.2
jupyterlab==4.0.7
jupyterlab-pygments==0.2.2
jupyterlab_server==2.24.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[W 2023-10-25 11:57:18.899 ServerApp] wrote error: 'Unhandled error'                                                                                          
    Traceback (most recent call last):                                                                                                                        
      File "/.../lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute                                     
        result = await result                                                                                                                                 
      File "/.../python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 311, in post            
        url_escape(checkpoint["id"]),                                                                                                                         
    TypeError: 'NoneType' object is not subscriptable                                                                                                         
[E 2023-10-25 11:57:18.900 ServerApp] {                                                                                                                       
      "Host": "localhost:8888",                                                                                                                               
      "Accept": "*/*",                                                                                                                                        
      "Referer": "http://localhost:8888/lab/workspaces/auto-i/tree/Untitled.ipynb",                                                                           
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by miraculixx** [comment]
Changing the `NoOpsCheckpoints` implementation slightly removes the issue (added the `checkpoint_model()` method and called this method in `create_file_checkpoint()` and `create_notebook_checkpoint()`, hint taken from FileContentsManager)

```
from IPython.utils.tz import utcnow
from jupyter_server.services.contents.checkpoints import GenericCheckpointsMixin, Checkpoints


class NoOpCheckpoints(GenericCheckpointsMixin, Checkpoints):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.log.info("**** NoOpCheckpoints initialized")

    def checkpoint_model(self):
        info = {
            "id": "",
            "last_modified": utcnow()
        }
        return info

    def create_file_checkpoint(self, content, format, path):
        """ -> checkpoint model"""
        return self.checkpoint_model()

    def create_notebook_checkpoint(self, nb, path):
        """ -> checkpoint model"""
        return self.checkpoint_model()

    def get_file_checkpoint(self, checkpoint_id, path):
        """ -> {'type': 'file', 'content': <str>, 'format': {'text', 'base64'}}"""

    def get_notebook_checkpoint(self, checkpoint_id, path):
        """ -> {'type': 'notebook', 'content': <output of nbformat.read>}"""

    def delete_checkpoint(self, checkpoint_id, path):
        """deletes a checkpoint for a file"""

    def list_checkpoints(self, path):
        """returns a list of checkpoint models for a given file,
        default just does one per file
        """
        return []

    def rename_checkpoint(self, checkpoint_id, old_path, new_path):
        """renames checkpoint from old path to new path"""

```
