### ISSUE TITLE
Server APIs failing behind nginx as reverse proxy

### ISSUE THREAD

**Issue by namangoel31** [jupyter-server/jupyter_server#1468]
## Description

I'm looking to integrate jupyter notebook using UI components from [Datalayer](https://jupyter-ui.datalayer.tech/) into my setup. It needs to be a single user jupyter server hosted on a private kubernetes cluster exposed via ALB. Between the Jupyter server and the ALB, sits nginx as reverse proxy. Current setup is described below:

## Reproduce
**Container:**
Ubuntu base image with jupyter_server, ipython, ipykernel, and jupyterlab.

**Jupyter config:**

```
import os
c = get_config()  #noqa
c.LabServerApp.open_browser = False
c.IdentityProvider.token = os.getenv("JUPYTER_TOKEN")
c.ServerApp.allow_credentials = True
ORIGIN="*"
c.ServerApp.allow_remote_access=True
c.ServerApp.disable_check_xsrf = False
c.ServerApp.ip = "0.0.0.0"
c.ServerApp.jpserver_extensions = {
    "jupyterlab": True,
}
c.ZMQChannelsWebsocketConnection.kernel_ws_protocol = None
c.ServerApp.log_level = "INFO"
c.ServerApp.port_retries = 0
c.FileContentsManager.preferred_dir = "/home/Notebooks"
c.ServerApp.root_dir = "/home/Notebooks"

c.ServerApp.tornado_settings = {
  "headers": {
    "Access-Control-Allow-Methods": "*",
    "Access-Control-Allow-Headers": "Accept, Accept-Encoding, Accept-Language, Authorization, Cache-Control, Connection, Content-Type, Host, Origin, Pragma, Referer, sec-ch-ua, sec-ch-ua-mobile, sec-ch-ua-platform, Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site, Upgrade, User-Agent, X-XSRFToken, X-Datalayer, Expires, X-CustomHeader, X-Service-Name",
    "Access-Control-Allow-Credentials": "true",
    "Content-Security-Policy": f"frame-ancestors "self" {ORIGIN} ",
  },
  "cookie_options": {
    "SameSite": "None",
    "Secure": True
  }
}
def upload_to_s3(model, os_path, contents_manager, **kwargs):
    ...
c.FileContentsManager.post_save_hook = upload_to_s3
```

**nginx conf:**
```
server {
    listen 80;
    listen [::]:80;
    server_name k8s.elb.amazonaws.com;
    client_body_in_file_only on;
    # Set this to match your frontend's URL
    #add_header 'Access-Control-Allow-Origin' 'http://sahiltest.gz.local.localhost:3000' always;
    add_header 'Access-Control-Allow-Headers' 'Authorization, Accept, Origin, DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Content-Range, Range, X-Service-Name' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
    #add_header 'Access-Control-Allow-Credentials' 'true' always; # Allow credentials

    resolver 172.20.0.10 valid=30s;

    location / {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Accept, Origin, DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Content-Range, Range, X-Service-Name' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always; # Allow credentials
            add_header 'Content-Length' 0;
            return 204; # No Content
        }

        proxy_pass http://jupyter_service_name.default.svc.cluster.local:8888;
        proxy_http_version 1.1;
	proxy_pass_request_headers on;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header Cookie $http_cookie;
    }
}
```

Browser Network tools show APIs failing.

- Operating System and version: Ubuntu 20.04 Jammy
- Browser and version: Any
- IPython          : 8.28.0
- ipykernel        : 6.29.5
- ipywidgets       : not installed
- jupyter_client   : 8.6.3
- jupyter_core     : 5.7.2
- jupyter_server   : 2.14.2
- jupyterlab       : 4.2.5
- nbclient         : 0.10.0
- nbconvert        : 7.16.4
- nbformat         : 5.10.4
- notebook         : not installed
- qtconsole        : not installed
- traitlets        : 5.14.3
- tornado        :6.2

**Comment by echarles** [comment]
Hi @namangoel31 There are a few components involved in your setup. What issues are you facing (can you share some logs)?

Maybe worth opening that question on the https://github.com/datalayer/jupyter-ui repository as the issue can be at any level.

**Comment by namangoel31** [comment]
Closing the issue as I'm not able to reproduce it.

**Comment by namangoel31** [comment]
I was able to reproduce the issue and here is some additional information:

**Jupyter logs:**
```
[W 2024-11-05 15:12:00.403 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:00.404 ServerApp] 403 GET /api/kernelspecs?1730819520306 (@10.0.7.218) 1.53ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:00.438 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:00.439 ServerApp] 403 GET /api/kernels?1730819520312 (@10.0.7.218) 0.67ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:00.468 TerminalsExtensionApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:00.468 TerminalsExtensionApp] 403 GET /api/terminals?1730819520313 (@10.0.7.218) 0.60ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:00.475 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:00.475 ServerApp] 403 GET /api/sessions?1730819520313 (@10.0.7.218) 0.63ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:00.476 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:00.476 ServerApp] 403 GET /api/me?1730819520307 (@10.0.7.218) 0.67ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:00.485 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:00.485 ServerApp] 403 GET /api/kernelspecs?1730819520389 (@10.0.7.218) 0.57ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:00.569 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3207, in wrapper
        raise HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:00.569 ServerApp] 403 POST /api/sessions?1730819520465 (@10.0.7.218) 0.66ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:02.612 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:02.612 ServerApp] 403 GET /api/kernels?1730819522517 (@10.0.7.218) 0.88ms referer=http://sahiltest.gz.local.localhost:3000/
[I 2024-11-05 15:12:03.279 ServerApp] 302 GET / (@10.0.7.218) 0.41ms
[W 2024-11-05 15:12:06.419 TerminalsExtensionApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:06.420 TerminalsExtensionApp] 403 GET /api/terminals?1730819526324 (@10.0.7.218) 0.83ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:10.032 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:10.033 ServerApp] 403 GET /api/sessions?1730819529930 (@10.0.7.218) 0.96ms referer=http://sahiltest.gz.local.localhost:3000/
[W 2024-11-05 15:12:10.543 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:10.544 ServerApp] 403 GET /api/kernels?1730819530449 (@10.0.7.218) 0.89ms referer=http://sahiltest.gz.local.localhost:3000/
[I 2024-11-05 15:12:11.999 ServerApp] 302 GET / (@10.0.7.218) 0.45ms
[I 2024-11-05 15:12:18.296 ServerApp] 302 GET / (@10.0.7.218) 0.43ms
[W 2024-11-05 15:12:22.137 TerminalsExtensionApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 3196, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 783, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-11-05 15:12:22.137 TerminalsExtensionApp] 403 GET /api/terminals?1730819542044 (@10.0.7.218) 0.94ms referer=http://sahiltest.gz.local.localhost:3000/
[I 2024-11-05 15:12:27.005 ServerApp] 302 GET / (@10.0.7.218) 0.45ms
```

**NGINX access logs:**
```
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "OPTIONS /api?1730819520082 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "GET /api?1730819520082 HTTP/1.1" 200 21 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "OPTIONS /api/kernelspecs?1730819520306 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "OPTIONS /api/kernels?1730819520312 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "GET /api/kernelspecs?1730819520306 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "OPTIONS /api/terminals?1730819520313 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "OPTIONS /api/sessions?1730819520313 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "OPTIONS /api/me?1730819520307 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "GET /api/kernels?1730819520312 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "OPTIONS /api/kernelspecs?1730819520389 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "GET /api/terminals?1730819520313 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "GET /api/sessions?1730819520313 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "GET /api/me?1730819520307 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "GET /api/kernelspecs?1730819520389 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "OPTIONS /api/sessions?1730819520465 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:00 +0000] "POST /api/sessions?1730819520465 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:02 +0000] "OPTIONS /api/kernels?1730819522517 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:02 +0000] "GET /api/kernels?1730819522517 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.1.65 - - [05/Nov/2024:15:12:03 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.2.154 - - [05/Nov/2024:15:12:06 +0000] "OPTIONS /api/terminals?1730819526324 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:06 +0000] "GET /api/terminals?1730819526324 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:09 +0000] "OPTIONS /api/sessions?1730819529930 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:10 +0000] "GET /api/sessions?1730819529930 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:10 +0000] "OPTIONS /api/kernels?1730819530449 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:10 +0000] "GET /api/kernels?1730819530449 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:11 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.1.65 - - [05/Nov/2024:15:12:18 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.2.154 - - [05/Nov/2024:15:12:22 +0000] "OPTIONS /api/terminals?1730819542044 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:22 +0000] "GET /api/terminals?1730819542044 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:27 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.2.154 - - [05/Nov/2024:15:12:29 +0000] "OPTIONS /api/kernels?1730819549068 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:29 +0000] "GET /api/kernels?1730819549068 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:30 +0000] "OPTIONS /api/sessions?1730819550281 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:30 +0000] "GET /api/sessions?1730819550281 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.1.65 - - [05/Nov/2024:15:12:33 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.2.154 - - [05/Nov/2024:15:12:42 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.1.65 - - [05/Nov/2024:15:12:48 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.2.154 - - [05/Nov/2024:15:12:49 +0000] "OPTIONS /api/kernelspecs?1730819568956 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:49 +0000] "GET /api/kernelspecs?1730819568956 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:57 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.2.154 - - [05/Nov/2024:15:12:59 +0000] "OPTIONS /api/kernels?1730819579548 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:12:59 +0000] "GET /api/kernels?1730819579548 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:13:00 +0000] "GET /api/events/subscribe?token=H3LL0W0RLD HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.1.65 - - [05/Nov/2024:15:13:03 +0000] "GET / HTTP/1.1" 302 0 "-" "ELB-HealthChecker/2.0" "-"
10.0.2.154 - - [05/Nov/2024:15:13:03 +0000] "OPTIONS /api/terminals?1730819583831 HTTP/1.1" 200 0 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
10.0.2.154 - - [05/Nov/2024:15:13:03 +0000] "GET /api/terminals?1730819583831 HTTP/1.1" 403 40 "http://sahiltest.gz.local.localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0" "49.43.169.48"
```

**Screenshot of browser network tools:**
![image](https://github.com/user-attachments/assets/d66fa83d-0a2b-4f31-af6c-19223ff4567d)

**Comment by namangoel31** [comment]
Edit: The setup seems to be working on firefox but not on MS Edge. I tried incognito and clearing cookies. No luck on Edge.

**Comment by echarles** [comment]
For incognito, you need to disable Block third-party cookies

![image](https://github.com/user-attachments/assets/8fa1bfb9-8d84-4342-8287-1698a0a02334)

Not sure about MS Edge.

**Comment by namangoel31** [comment]
It was already disabled in MS Edge. 
Also, Chrome and Brave give CORS error: allow origin mismatch.
