### ISSUE TITLE
Issue trusting notebook (using nbclassic)

### ISSUE THREAD

**Issue by vidartf** [jupyter-server/jupyter_server#372]
I recently ran nbclassic to test some things, and found that I needed to manually mark a notebook as trusted to render some outputs (as it should be). However, clicking the "trust" button, I get this trace in the server log:
```python
[I 2021-01-05 10:23:04.183 ServerApp] Saving file at /ipyscales/examples/scaled-values.ipynb
[W 2021-01-05 10:23:04.507 ServerApp] Trusting notebook /ipyscales/examples/scaled-values.ipynb
[E 2021-01-05 10:23:04.555 ServerApp] Uncaught exception POST /api/contents/ipyscales/examples/scaled-values.ipynb/trust (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/contents/ipyscales/examples/scaled-values.ipynb/trust', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "<env root>\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "<env root>\lib\site-packages\jupyter_server\services\contents\handlers.py", line 297, in post
        await cm.trust_notebook(path)
    TypeError: object NoneType can't be used in 'await' expression
[E 2021-01-05 10:23:04.563 ServerApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Sec-Ch-Ua": "\"Google Chrome\";v=\"87\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"87\"",
      "Dnt": "1",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "<value>",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/notebooks/ipyscales/examples/scaled-values.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en,en-GB;q=0.9,en-US;q=0.8,no;q=0.7",
      "Cookie": "<value>"
    }
[E 2021-01-05 10:23:04.565 ServerApp] 500 POST /api/contents/ipyscales/examples/scaled-values.ipynb/trust (::1) 133.01ms referer=http://localhost:8888/notebooks/ipyscales/examples/scaled-values.ipynb
```

**Comment by vidartf** [comment]
(I'm using jupyter-server=1.1.3 here)
