### ISSUE TITLE
Mashing Ctrl-C results in an UnboundLocalError

### ISSUE THREAD

**Issue by ianhi** [jupyter-server/jupyter_server#439]
I have always shut down jupyter applications by hitting `Ctrl-C` twice. For a long time this seemed to work fine, however recently I've noticed that doing so so results is this error:

```
Traceback (most recent call last):
  File "/home/ian/mambaforge/envs/micro/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 520, in launch_instance
    serverapp.start()
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2101, in start
    self.start_ioloop()
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2093, in start_ioloop
    self._cleanup()
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2078, in _cleanup
    self.cleanup_kernels()
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1847, in cleanup_kernels
    run_sync(self.kernel_manager.shutdown_all())
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/jupyter_server/utils.py", line 228, in run_sync
    return wrapped()
  File "/home/ian/mambaforge/envs/micro/lib/python3.8/site-packages/jupyter_server/utils.py", line 227, in wrapped
    return result
UnboundLocalError: local variable 'result' referenced before assignment
```

## Reproduce
I'm not sure the exact situation that reproduces this. Just opening jupyterlab is inadequate, but this tends to happen to me after a day of work with multiple open notebooks. However, it is clear that this is a risk as there is an `if` without a corresponding `else` in the code:

https://github.com/jupyter-server/jupyter_server/blob/36218db5f08b08e41f1cff36f40a29adb146f81e/jupyter_server/utils.py#L222-L227

## Environment:

`conda list | grep jupyter`
```
jupyter-packaging         0.7.12             pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
jupyter_server            1.4.1            py38h578d9bd_0    conda-forge
jupyterlab                3.0.9              pyhd8ed1ab_0    conda-forge
jupyterlab-code-formatter 1.4.4                    pypi_0    pypi
jupyterlab-vim            0.13.4                   pypi_0    pypi
jupyterlab-vimrc          0.5.2                    pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
```

**Comment by blink1073** [comment]
This code as moved to `jupyter_core` and now returns in the referenced [if block](https://github.com/jupyter/jupyter_core/blob/eb65690cb69a793edeb21b520c2358332933bb5d/jupyter_core/utils/__init__.py#L186), closing as fixed.
