### ISSUE TITLE
SQLite objects created in a thread Exception

### ISSUE THREAD

**Issue by Zsailer** [jupyter-server/jupyter_server#790]
Seeing the following exception periodically in the tests.

For example, see this failed test action: https://github.com/jupyter-server/jupyter_server/runs/6027513680?check_suite_focus=true

Test name is: `test_modify_path[jp_server_config2]`

```python
  Traceback (most recent call last):
    File "/home/runner/work/jupyter_server/jupyter_server/sdist/test/jupyter_server/services/sessions/sessionmanager.py", line 227, in __del__
      self.close()
    File "/home/runner/work/jupyter_server/jupyter_server/sdist/test/jupyter_server/services/sessions/sessionmanager.py", line 222, in close
      self._cursor.close()
  sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140546998728512 and this is thread id 140545254971136.
```

**Comment by bollwyvl** [comment]
Perhaps the `jp_serverapp` fixture (and maybe others) should close the `session_manager` (and maybe more things)?

```py
@pytest.fixture(scope="function")
def jp_serverapp(jp_ensure_app_fixture, jp_server_config, jp_argv, jp_configurable_serverapp):
    """Starts a Jupyter Server instance based on the established configuration values."""
    app = jp_configurable_serverapp(config=jp_server_config, argv=jp_argv)
    yield app
    app.remove_server_info_file()
    app.remove_browser_open_files()
    app.session_manager.close() # like this, but maybe more stuff
```
